### PR TITLE
Change invokeFail to invokeFinish if limit reached.

### PR DESCRIPTION
**Pull request by RagnarR**

### CODE REVIEW

**Comment by RagnarR** [comment]
[(2) Refactor URLDriller to handle redirects](https://trello.com/c/NlMY9wUv/27-2-refactor-urldriller-to-handle-redirects)

**Comment by dvmrmc** [comment]
also remove the default limit to 15 if you don't configure one. and let's leave a method `void doDrill(String url)` that will do infinite redirections.

**Review by dvmrmc — CHANGES_REQUESTED** [review]
read comment above

**Review by dvmrmc — APPROVED** [review]
awesome

**Pull request merged**
